# http://linux.die.net/man/5/rackspace_yum.conf
case node[:platform_version].to_i
when 5
  default[:rackspace_yum][:main][:cachedir] = '/var/cache/yum'
else
  default[:rackspace_yum][:main][:cachedir] = '/var/cache/yum/$basearch/$releasever'
end

default[:rackspace_yum][:main][:cookbook_template_globalconfig] = 'rackspace_yum'
default[:rackspace_yum][:main][:cookbook_template_repository] = 'rackspace_yum'
default[:rackspace_yum][:main][:distroverpkg] = "#{node[:platform]}-release"
default[:rackspace_yum][:main][:gpgcheck] = true # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:keepcache] = false # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:logfile] = '/var/log/yum.log' # /.*/
default[:rackspace_yum][:main][:path] = '/etc/yum.conf' #  /.*/
default[:rackspace_yum][:main][:tolerant] = false

default[:rackspace_yum][:main][:alwaysprompt] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:assumeyes] = nil  # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:bandwidth] = nil # /^\d+$/
default[:rackspace_yum][:main][:bugtracker_url] = nil # /.*/
default[:rackspace_yum][:main][:clean_requirements_on_remove] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:color] = nil # %w{ always never }
default[:rackspace_yum][:main][:color_list_available_downgrade] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_available_install] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_available_reinstall] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_available_upgrade] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_installed_extra] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_installed_newer] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_installed_older] = nil #  /.*/
default[:rackspace_yum][:main][:color_list_installed_reinstall] = nil #  /.*/
default[:rackspace_yum][:main][:color_search_match] = nil #  /.*/
default[:rackspace_yum][:main][:color_update_installed] = nil #  /.*/
default[:rackspace_yum][:main][:color_update_local] = nil #  /.*/
default[:rackspace_yum][:main][:color_update_remote] = nil #  /.*/
default[:rackspace_yum][:main][:commands] = nil #  /.*/
default[:rackspace_yum][:main][:debuglevel] = nil # /^\d+$/
default[:rackspace_yum][:main][:diskspacecheck] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:enable_group_conditionals] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:errorlevel] = nil # /^\d+$/
default[:rackspace_yum][:main][:exactarch] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:exclude] = nil # /.*/
default[:rackspace_yum][:main][:group_package_types] = nil # /.*/
default[:rackspace_yum][:main][:groupremove_leaf_only] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:history_list_view] = nil #  /.*/
default[:rackspace_yum][:main][:history_record] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:history_record_packages] = nil #  /.*/
default[:rackspace_yum][:main][:http_caching] = nil # %w{ packages all none }
default[:rackspace_yum][:main][:installonly_limit] = nil # /\d+/, /keep/
default[:rackspace_yum][:main][:installonlypkgs] = nil # /.*/
default[:rackspace_yum][:main][:installroot] = nil # /.*/
default[:rackspace_yum][:main][:keepalive] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:kernelpkgnames] = nil # /.*/
default[:rackspace_yum][:main][:localpkg_gpgcheck] = nil # [TrueClass,# FalseClass]
default[:rackspace_yum][:main][:max_retries] = nil # /^\d+$/
default[:rackspace_yum][:main][:mdpolicy] = nil # %w{ packages all none }
default[:rackspace_yum][:main][:metadata_expire] = nil # /^\d+$/
default[:rackspace_yum][:main][:mirrorlist_expire] = nil # /^\d+$/
default[:rackspace_yum][:main][:multilib_policy] = nil # %w{ all best }
default[:rackspace_yum][:main][:obsoletes] = nil  # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:overwrite_groups] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:password] = nil #  /.*/
default[:rackspace_yum][:main][:persistdir] = nil # /.*/
default[:rackspace_yum][:main][:pluginconfpath] = nil #  /.*/
default[:rackspace_yum][:main][:pluginpath] = nil #  /.*/
default[:rackspace_yum][:main][:plugins] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:protected_multilib] = nil # /.*/
default[:rackspace_yum][:main][:protected_packages] = nil # /.*/
default[:rackspace_yum][:main][:proxy] = nil #  /.*/
default[:rackspace_yum][:main][:proxy_password] = nil #  /.*/
default[:rackspace_yum][:main][:proxy_username] = nil #  /.*/
default[:rackspace_yum][:main][:recent] = nil # /^\d+$/
default[:rackspace_yum][:main][:repo_gpgcheck] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:reset_nice] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:rpmverbosity] = nil # %w{ info critical# emergency error warn debug }
default[:rackspace_yum][:main][:showdupesfromrepos] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:skip_broken] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:ssl_check_cert_permissions] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:sslcacert] = nil # /.*/
default[:rackspace_yum][:main][:sslclientcert] = nil # /.*/
default[:rackspace_yum][:main][:sslclientkey] = nil #  /.*/
default[:rackspace_yum][:main][:sslverify] = nil # [TrueClass, FalseClass]
default[:rackspace_yum][:main][:syslog_device] = nil #  /.*/
default[:rackspace_yum][:main][:syslog_facility] = nil #  /.*/
default[:rackspace_yum][:main][:syslog_ident] = nil #  /.*/
default[:rackspace_yum][:main][:throttle] = nil # [/\d+k/, /\d+M/, /\d+G/]
default[:rackspace_yum][:main][:timeout] = nil # /\d+/
default[:rackspace_yum][:main][:tsflags] = nil # /.*/
default[:rackspace_yum][:main][:username] = nil #  /.*/
